### ISSUE TITLE
OHRI Technical Road Map (Form Engine/ Form Builder)

### ISSUE THREAD

**Issue by kajambiya** [openmrs/openmrs-form-engine-lib#131]
### Feature Work
- [ ] **Form Engine (Parity with Angular form engine)**
  - [x] Support rendering type "drug"
  - [x] Ability to mark a form field as transient.
  - [x] Support injecting of external data sources.
  - [x] Support registration of custom expressions.
  - [ ] Support for creation of reusable components.
  - [ ] Support for rendering problem by concept class.
  - [x] Support for file attachment rendering.
  - [ ] Concept location support.
  - [ ] Adjust the rest-web-services module to allow filtering of voided forms.
  - [ ] Form submission should use the `form_uuid `and `encounter_uuid `fetched from the backend.
  - [ ] Support for Z function as part of inbuilt Expression helpers.
  - [ ] Support translation/localisation (i18n) in labels.
  - [ ] Support for Drug Orders.
- [ ] **Form Builder**
  - [x] Display of Audit information on the form editor.
  - [ ] Support for referencing reusable components.

### Bugs
- [ ] **Form Engine**
  - [x] Previous values are picked from old encounters. 
 
### House Keeping
- [ ] **Form Engine**
  - [ ] Update Form Engine Documentation.
  - [ ] Comparison of validation in RFE against AFE.

**Comment by vishisht-dubey** [comment]
Hey @gracepotma can i work on this??

**Comment by samuelmale** [comment]
Feel free to pickup at ticket: https://openmrs.atlassian.net/browse/O3-2193
